[rospy.client][INFO] 2015-05-22 09:08:54,269: init_node, name[/activity_manager], pid[26199]
[xmlrpc][INFO] 2015-05-22 09:08:54,278: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 09:08:54,278: Started XML-RPC server [http://192.168.1.13:35457/]
[rospy.init][INFO] 2015-05-22 09:08:54,278: ROS Slave URI: [http://192.168.1.13:35457/]
[rospy.impl.masterslave][INFO] 2015-05-22 09:08:54,278: _ready: http://192.168.1.13:35457/
[rospy.registration][INFO] 2015-05-22 09:08:54,279: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2015-05-22 09:08:54,279: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2015-05-22 09:08:54,379: registered with master
[rospy.rosout][INFO] 2015-05-22 09:08:54,379: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 09:08:54,382: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 09:08:54,383: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2015-05-22 09:08:54,416: topic[/activity] adding connection to [/log], count 0
[rosout][INFO] 2015-05-22 09:08:54,419: Starting new timer
[rosout][INFO] 2015-05-22 09:08:54,420: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 09:08:54,447: topic[/activity] adding connection to [http://192.168.1.13:35457/], count 0
[rospy.internal][INFO] 2015-05-22 09:08:54,454: topic[/activity] adding connection to [/activity_manager], count 1
[rospy.internal][INFO] 2015-05-22 09:08:54,603: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2015-05-22 09:08:54,819: Haven't received a clear on 'watchdog_clear/tablet' topic
[rospy.internal][INFO] 2015-05-22 09:08:55,534: topic[/activity] adding connection to [/joke_nao], count 2
[rospy.internal][INFO] 2015-05-22 09:08:55,669: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2015-05-22 09:08:55,742: topic[/activity] adding connection to [/learning_words_nao], count 4
[rospy.internal][INFO] 2015-05-22 09:08:55,763: topic[/activity] adding connection to [http://192.168.1.13:33383/], count 1
[rosout][INFO] 2015-05-22 09:08:56,423: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 09:09:03,462: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 09:09:03,964: STATE: STARTING_INTERACTION
[rosout][INFO] 2015-05-22 09:09:09,477: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 09:09:10,980: STATE: ACTIVITY
[rospy.internal][INFO] 2015-05-22 09:10:04,878: topic[/activity_time] adding connection to [/emotional_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:10:04,976: topic[/activity] adding connection to [http://192.168.1.13:60214/], count 2
[rospy.internal][ERROR] 2015-05-22 09:11:12,001: Unable to initiate TCP/IP socket to 192.168.1.13:34075 (http://192.168.1.13:60214/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 09:11:12,005: topic[/activity_time] adding connection to [/emotional_manager], count 1
[rospy.internal][INFO] 2015-05-22 09:11:12,005: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][WARNING] 2015-05-22 09:11:13,003: Unknown error initiating TCP/IP socket to 192.168.1.13:34075 (http://192.168.1.13:60214/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:11:13,003: topic[/activity] removing connection to http://192.168.1.13:60214/
[rospy.internal][INFO] 2015-05-22 09:11:13,632: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][INFO] 2015-05-22 09:11:55,941: topic[/stop_learning] adding connection to [http://192.168.1.13:42342/], count 0
[rosout][INFO] 2015-05-22 09:11:57,662: STATE: STOPPING
[rospy.internal][ERROR] 2015-05-22 09:11:58,882: Unable to initiate TCP/IP socket to 192.168.1.13:50766 (http://192.168.1.13:42342/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 09:11:59,884: Unknown error initiating TCP/IP socket to 192.168.1.13:50766 (http://192.168.1.13:42342/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:11:59,884: topic[/stop_learning] removing connection to http://192.168.1.13:42342/
[rospy.internal][ERROR] 2015-05-22 09:12:00,608: Unable to initiate TCP/IP socket to 192.168.1.13:56066 (http://192.168.1.13:33383/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 09:12:00,615: topic[/activity] adding connection to [/learning_words_nao], count 5
[rospy.internal][INFO] 2015-05-22 09:12:00,615: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][WARNING] 2015-05-22 09:12:01,609: Unknown error initiating TCP/IP socket to 192.168.1.13:56066 (http://192.168.1.13:33383/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:12:01,610: topic[/activity] removing connection to http://192.168.1.13:33383/
[rospy.core][INFO] 2015-05-22 09:12:03,324: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 09:12:03,335: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 09:12:03,335: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 09:12:03,336: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2015-05-22 09:12:03,337: topic[/activity] removing connection to /joke_nao
[rospy.internal][ERROR] 2015-05-22 09:12:03,338: Unable to initiate TCP/IP socket to 192.168.1.13:41008 (http://192.168.1.13:35457/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 09:12:03,338: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 09:12:03,339: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 09:12:03,339: topic[/activity] removing connection to http://192.168.1.13:35457/
[rospy.impl.masterslave][INFO] 2015-05-22 09:12:03,339: Interaction exited
[rosout][INFO] 2015-05-22 09:12:03,471: Stopped
[rospy.core][INFO] 2015-05-22 09:12:03,501: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 09:13:09,046: init_node, name[/activity_manager], pid[27404]
[xmlrpc][INFO] 2015-05-22 09:13:09,047: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2015-05-22 09:13:09,047: ROS Slave URI: [http://192.168.1.13:54665/]
[xmlrpc][INFO] 2015-05-22 09:13:09,047: Started XML-RPC server [http://192.168.1.13:54665/]
[rospy.impl.masterslave][INFO] 2015-05-22 09:13:09,048: _ready: http://192.168.1.13:54665/
[xmlrpc][INFO] 2015-05-22 09:13:09,048: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 09:13:09,048: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 09:13:09,148: registered with master
[rospy.rosout][INFO] 2015-05-22 09:13:09,148: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 09:13:09,150: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 09:13:09,151: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 09:13:09,166: Starting new timer
[rospy.internal][INFO] 2015-05-22 09:13:09,168: topic[/activity] adding connection to [http://192.168.1.13:54665/], count 0
[rosout][INFO] 2015-05-22 09:13:09,169: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 09:13:09,171: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:13:09,222: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2015-05-22 09:13:09,392: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2015-05-22 09:13:09,569: Haven't received a clear on 'watchdog_clear/tablet' topic
[rospy.internal][INFO] 2015-05-22 09:13:09,933: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2015-05-22 09:13:09,938: topic[/activity] adding connection to [http://192.168.1.13:52480/], count 1
[rospy.internal][INFO] 2015-05-22 09:13:09,973: topic[/activity] adding connection to [/joke_nao], count 3
[rospy.internal][INFO] 2015-05-22 09:13:10,135: topic[/activity] adding connection to [/learning_words_nao], count 4
[rosout][INFO] 2015-05-22 09:13:11,171: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 09:13:13,144: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 09:13:13,645: STATE: STARTING_INTERACTION
[rosout][INFO] 2015-05-22 09:13:21,373: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 09:13:22,875: STATE: ACTIVITY
[rospy.internal][INFO] 2015-05-22 09:13:30,625: topic[/activity_time] adding connection to [/emotional_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:13:30,709: topic[/activity] adding connection to [http://192.168.1.13:33859/], count 2
[rospy.internal][INFO] 2015-05-22 09:15:25,447: topic[/stop_learning] adding connection to [http://192.168.1.13:35972/], count 0
[rospy.internal][ERROR] 2015-05-22 09:15:25,486: Unable to initiate TCP/IP socket to 192.168.1.13:51672 (http://192.168.1.13:33859/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2015-05-22 09:15:25,990: STATE: STOPPING
[rospy.internal][WARNING] 2015-05-22 09:15:26,491: Unknown error initiating TCP/IP socket to 192.168.1.13:51672 (http://192.168.1.13:33859/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:15:26,492: topic[/activity] removing connection to http://192.168.1.13:33859/
[rospy.internal][ERROR] 2015-05-22 09:15:28,385: Unable to initiate TCP/IP socket to 192.168.1.13:41410 (http://192.168.1.13:35972/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 09:15:29,387: Unknown error initiating TCP/IP socket to 192.168.1.13:41410 (http://192.168.1.13:35972/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:15:29,388: topic[/stop_learning] removing connection to http://192.168.1.13:35972/
[rospy.internal][ERROR] 2015-05-22 09:15:30,074: Unable to initiate TCP/IP socket to 192.168.1.13:34424 (http://192.168.1.13:52480/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2015-05-22 09:15:30,076: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2015-05-22 09:15:30,077: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2015-05-22 09:15:30,802: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2015-05-22 09:15:30,803: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2015-05-22 09:15:31,076: Unknown error initiating TCP/IP socket to 192.168.1.13:34424 (http://192.168.1.13:52480/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:15:31,077: topic[/activity] removing connection to http://192.168.1.13:52480/
[rospy.core][INFO] 2015-05-22 09:15:31,734: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 09:15:31,744: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 09:15:31,744: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2015-05-22 09:15:31,744: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 09:15:31,745: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 09:15:31,745: topic[/activity] removing connection to /joke_nao
[rospy.internal][ERROR] 2015-05-22 09:15:31,746: Unable to initiate TCP/IP socket to 192.168.1.13:48374 (http://192.168.1.13:54665/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 09:15:31,746: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 09:15:31,746: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][INFO] 2015-05-22 09:15:31,746: topic[/activity] removing connection to http://192.168.1.13:54665/
[rospy.impl.masterslave][INFO] 2015-05-22 09:15:31,747: Interaction exited
[rosout][INFO] 2015-05-22 09:15:31,862: Stopped
[rospy.core][INFO] 2015-05-22 09:15:31,890: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 09:17:55,138: init_node, name[/activity_manager], pid[28969]
[xmlrpc][INFO] 2015-05-22 09:17:55,148: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 09:17:55,148: Started XML-RPC server [http://192.168.1.13:33785/]
[rospy.impl.masterslave][INFO] 2015-05-22 09:17:55,148: _ready: http://192.168.1.13:33785/
[rospy.registration][INFO] 2015-05-22 09:17:55,150: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2015-05-22 09:17:55,150: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2015-05-22 09:17:55,151: ROS Slave URI: [http://192.168.1.13:33785/]
[rospy.init][INFO] 2015-05-22 09:17:55,151: registered with master
[rospy.rosout][INFO] 2015-05-22 09:17:55,151: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 09:17:55,154: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 09:17:55,156: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 09:17:55,207: Starting new timer
[rosout][INFO] 2015-05-22 09:17:55,208: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 09:17:55,233: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:17:55,235: topic[/activity] adding connection to [http://192.168.1.13:33785/], count 0
[rospy.internal][INFO] 2015-05-22 09:17:55,308: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2015-05-22 09:17:55,309: topic[/watchdog_clear/tablet] adding connection to [http://192.168.1.3:33845/], count 0
[rospy.internal][INFO] 2015-05-22 09:17:55,311: topic[/activity] adding connection to [http://192.168.1.16:53703/], count 1
[rospy.internal][INFO] 2015-05-22 09:17:55,330: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 09:17:56,346: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2015-05-22 09:17:56,391: topic[/activity] adding connection to [/joke_nao], count 3
[rospy.internal][INFO] 2015-05-22 09:17:56,391: topic[/activity] adding connection to [http://192.168.1.13:56476/], count 2
[rospy.internal][INFO] 2015-05-22 09:17:56,651: topic[/activity] adding connection to [/learning_words_nao], count 4
[rosout][INFO] 2015-05-22 09:17:57,210: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 09:17:57,833: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:17:57,836: Re-connection
[rosout][INFO] 2015-05-22 09:17:58,648: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 09:17:59,150: STATE: STARTING_INTERACTION
[rosout][INFO] 2015-05-22 09:18:07,422: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 09:18:08,925: STATE: ACTIVITY
[rosout][INFO] 2015-05-22 09:21:55,574: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:21:55,587: Re-connection
[rosout][INFO] 2015-05-22 09:25:46,920: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:25:46,921: Re-connection
[rospy.internal][INFO] 2015-05-22 09:27:32,052: topic[/stop_learning] adding connection to [http://192.168.1.13:60387/], count 0
[rosout][INFO] 2015-05-22 09:27:33,480: STATE: STOPPING
[rospy.internal][ERROR] 2015-05-22 09:27:35,021: Unable to initiate TCP/IP socket to 192.168.1.13:44674 (http://192.168.1.13:60387/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 09:27:36,023: Unknown error initiating TCP/IP socket to 192.168.1.13:44674 (http://192.168.1.13:60387/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:27:36,024: topic[/stop_learning] removing connection to http://192.168.1.13:60387/
[rospy.internal][ERROR] 2015-05-22 09:27:36,811: Unable to initiate TCP/IP socket to 192.168.1.13:43846 (http://192.168.1.13:56476/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 09:27:37,812: Unknown error initiating TCP/IP socket to 192.168.1.13:43846 (http://192.168.1.13:56476/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:27:37,812: topic[/activity] removing connection to http://192.168.1.13:56476/
[rospy.core][INFO] 2015-05-22 09:27:41,264: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 09:27:41,273: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 09:27:41,274: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2015-05-22 09:27:41,275: topic[/activity] removing connection to /log
[rospy.internal][ERROR] 2015-05-22 09:27:41,275: Unable to initiate TCP/IP socket to 192.168.1.13:39860 (http://192.168.1.13:33785/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 09:27:41,276: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 09:27:41,277: topic[/activity] removing connection to /joke_nao
[rospy.internal][INFO] 2015-05-22 09:27:41,277: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 09:27:41,277: topic[/activity] removing connection to http://192.168.1.13:33785/
[rospy.internal][INFO] 2015-05-22 09:27:41,277: topic[/activity] removing connection to http://192.168.1.16:53703/
[rospy.internal][INFO] 2015-05-22 09:27:41,278: topic[/watchdog_clear/tablet] removing connection to http://192.168.1.3:33845/
[rospy.impl.masterslave][INFO] 2015-05-22 09:27:41,278: Interaction exited
[rosout][INFO] 2015-05-22 09:27:41,382: Stopped
[rospy.core][INFO] 2015-05-22 09:27:41,414: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 09:28:07,255: init_node, name[/activity_manager], pid[15362]
[xmlrpc][INFO] 2015-05-22 09:28:07,256: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2015-05-22 09:28:07,256: ROS Slave URI: [http://192.168.1.13:39754/]
[xmlrpc][INFO] 2015-05-22 09:28:07,256: Started XML-RPC server [http://192.168.1.13:39754/]
[rospy.impl.masterslave][INFO] 2015-05-22 09:28:07,257: _ready: http://192.168.1.13:39754/
[xmlrpc][INFO] 2015-05-22 09:28:07,257: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 09:28:07,257: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 09:28:07,357: registered with master
[rospy.rosout][INFO] 2015-05-22 09:28:07,358: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 09:28:07,360: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 09:28:07,361: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 09:28:07,386: Starting new timer
[rosout][INFO] 2015-05-22 09:28:07,386: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 09:28:07,427: topic[/activity] adding connection to [http://192.168.1.13:39754/], count 0
[rospy.internal][INFO] 2015-05-22 09:28:07,430: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:28:07,465: topic[/watchdog_clear/tablet] adding connection to [http://192.168.1.3:33845/], count 0
[rospy.internal][INFO] 2015-05-22 09:28:07,483: topic[/activity] adding connection to [http://192.168.1.16:53703/], count 1
[rospy.internal][INFO] 2015-05-22 09:28:07,512: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2015-05-22 09:28:07,564: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 09:28:08,486: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2015-05-22 09:28:08,593: topic[/activity] adding connection to [http://192.168.1.13:49664/], count 2
[rospy.internal][INFO] 2015-05-22 09:28:08,736: topic[/activity] adding connection to [/learning_words_nao], count 3
[rospy.internal][INFO] 2015-05-22 09:28:08,839: topic[/activity] adding connection to [/joke_nao], count 4
[rosout][INFO] 2015-05-22 09:28:09,388: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 09:28:11,075: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 09:28:11,576: STATE: STARTING_INTERACTION
[rospy.internal][INFO] 2015-05-22 09:28:18,180: topic[/activity_time] adding connection to [/emotional_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:28:18,196: topic[/activity] adding connection to [http://192.168.1.13:60095/], count 3
[rospy.internal][INFO] 2015-05-22 09:28:18,642: topic[/activity] adding connection to [/action_manager], count 5
[rosout][INFO] 2015-05-22 09:28:19,568: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 09:28:21,070: STATE: ACTIVITY
[rosout][INFO] 2015-05-22 09:28:45,264: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:28:47,471: Re-connection
[rosout][INFO] 2015-05-22 09:29:11,644: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:29:11,679: Re-connection
[rospy.internal][INFO] 2015-05-22 09:29:19,406: topic[/activity] adding connection to [/learning_words_nao], count 6
[rospy.internal][INFO] 2015-05-22 09:29:19,406: topic[/activity] removing connection to /learning_words_nao
[rosout][INFO] 2015-05-22 09:29:57,890: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:29:57,899: Re-connection
[rospy.internal][ERROR] 2015-05-22 09:30:09,678: Unable to initiate TCP/IP socket to 192.168.1.13:59765 (http://192.168.1.13:60095/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 09:30:09,683: topic[/stop_learning] adding connection to [http://192.168.1.13:60622/], count 0
[rospy.internal][INFO] 2015-05-22 09:30:09,687: topic[/activity_time] adding connection to [/emotional_manager], count 1
[rospy.internal][INFO] 2015-05-22 09:30:09,687: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][WARNING] 2015-05-22 09:30:10,680: Unknown error initiating TCP/IP socket to 192.168.1.13:59765 (http://192.168.1.13:60095/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rosout][INFO] 2015-05-22 09:30:10,678: STATE: STOPPING
[rospy.internal][INFO] 2015-05-22 09:30:10,681: topic[/activity] removing connection to http://192.168.1.13:60095/
[rospy.internal][ERROR] 2015-05-22 09:30:12,636: Unable to initiate TCP/IP socket to 192.168.1.13:42077 (http://192.168.1.13:60622/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 09:30:13,638: Unknown error initiating TCP/IP socket to 192.168.1.13:42077 (http://192.168.1.13:60622/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:30:13,638: topic[/stop_learning] removing connection to http://192.168.1.13:60622/
[rospy.internal][ERROR] 2015-05-22 09:30:14,042: Unable to initiate TCP/IP socket to 192.168.1.13:34907 (http://192.168.1.13:49664/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 09:30:15,043: Unknown error initiating TCP/IP socket to 192.168.1.13:34907 (http://192.168.1.13:49664/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 09:30:15,044: topic[/activity] removing connection to http://192.168.1.13:49664/
[rospy.core][INFO] 2015-05-22 09:30:16,395: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 09:30:16,404: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 09:30:16,405: topic[/activity] removing connection to /activity_manager
[rospy.internal][ERROR] 2015-05-22 09:30:16,405: Unable to initiate TCP/IP socket to 192.168.1.13:57139 (http://192.168.1.13:39754/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 09:30:16,405: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 09:30:16,406: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 09:30:16,406: topic[/activity] removing connection to /joke_nao
[rospy.internal][INFO] 2015-05-22 09:30:16,406: topic[/activity] removing connection to /action_manager
[rospy.internal][INFO] 2015-05-22 09:30:16,406: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 09:30:16,406: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][INFO] 2015-05-22 09:30:16,406: topic[/activity] removing connection to http://192.168.1.13:39754/
[rospy.internal][INFO] 2015-05-22 09:30:16,407: topic[/activity] removing connection to http://192.168.1.16:53703/
[rospy.internal][INFO] 2015-05-22 09:30:16,407: topic[/watchdog_clear/tablet] removing connection to http://192.168.1.3:33845/
[rospy.impl.masterslave][INFO] 2015-05-22 09:30:16,407: Interaction exited
[rosout][INFO] 2015-05-22 09:30:16,571: Stopped
[rospy.core][INFO] 2015-05-22 09:30:16,602: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 09:45:28,049: init_node, name[/activity_manager], pid[21133]
[xmlrpc][INFO] 2015-05-22 09:45:28,050: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 09:45:28,051: Started XML-RPC server [http://192.168.1.13:50638/]
[rospy.impl.masterslave][INFO] 2015-05-22 09:45:28,051: _ready: http://192.168.1.13:50638/
[rospy.init][INFO] 2015-05-22 09:45:28,051: ROS Slave URI: [http://192.168.1.13:50638/]
[xmlrpc][INFO] 2015-05-22 09:45:28,051: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 09:45:28,051: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 09:45:28,151: registered with master
[rospy.rosout][INFO] 2015-05-22 09:45:28,151: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 09:45:28,153: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 09:45:28,154: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 09:45:28,173: Starting new timer
[rosout][INFO] 2015-05-22 09:45:28,174: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 09:45:28,175: topic[/activity] adding connection to [http://192.168.1.13:50638/], count 0
[rospy.internal][INFO] 2015-05-22 09:45:28,177: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:45:28,227: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2015-05-22 09:45:28,289: topic[/activity] adding connection to [http://192.168.1.16:53703/], count 1
[rospy.internal][INFO] 2015-05-22 09:45:28,289: topic[/watchdog_clear/tablet] adding connection to [http://192.168.1.3:33845/], count 0
[rospy.internal][INFO] 2015-05-22 09:45:28,326: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 09:45:28,745: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2015-05-22 09:45:28,747: topic[/activity] adding connection to [http://192.168.1.13:54529/], count 2
[rospy.internal][INFO] 2015-05-22 09:45:29,067: topic[/activity] adding connection to [/joke_nao], count 3
[rospy.internal][INFO] 2015-05-22 09:45:29,318: topic[/activity] adding connection to [/learning_words_nao], count 4
[rosout][INFO] 2015-05-22 09:45:30,177: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 09:45:30,838: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:45:30,839: Re-connection
[rosout][INFO] 2015-05-22 09:45:31,692: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 09:45:32,193: STATE: STARTING_INTERACTION
[rosout][INFO] 2015-05-22 09:45:39,991: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 09:45:41,494: STATE: ACTIVITY
[rospy.internal][INFO] 2015-05-22 09:45:53,891: topic[/activity_time] adding connection to [/emotional_manager], count 0
[rospy.internal][INFO] 2015-05-22 09:45:53,966: topic[/activity] adding connection to [http://192.168.1.13:41917/], count 3
[rospy.internal][INFO] 2015-05-22 09:45:53,983: topic[/activity] adding connection to [/action_manager], count 5
[rosout][INFO] 2015-05-22 09:46:02,857: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:46:03,023: Re-connection
[rosout][INFO] 2015-05-22 09:46:17,203: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:46:17,250: Re-connection
[rosout][INFO] 2015-05-22 09:46:18,390: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:46:18,520: Re-connection
[rosout][INFO] 2015-05-22 09:46:29,624: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:46:32,068: Re-connection
[rosout][INFO] 2015-05-22 09:46:54,395: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:46:56,899: Re-connection
[rosout][INFO] 2015-05-22 09:47:12,384: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:47:12,440: Re-connection
[rosout][INFO] 2015-05-22 09:47:15,953: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:47:18,455: Re-connection
[rosout][INFO] 2015-05-22 09:47:35,997: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:47:38,453: Re-connection
[rosout][INFO] 2015-05-22 09:47:53,055: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:47:55,521: Re-connection
[rosout][INFO] 2015-05-22 09:48:10,195: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:48:12,506: Re-connection
[rosout][INFO] 2015-05-22 09:48:33,653: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:48:36,071: Re-connection
[rosout][INFO] 2015-05-22 09:48:51,614: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:48:54,081: Re-connection
[rosout][INFO] 2015-05-22 09:49:07,947: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:49:07,973: Re-connection
[rosout][INFO] 2015-05-22 09:49:11,149: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:49:13,556: Re-connection
[rosout][INFO] 2015-05-22 09:49:27,233: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:49:29,310: Re-connection
[rosout][INFO] 2015-05-22 09:49:36,612: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:49:37,037: Re-connection
[rosout][INFO] 2015-05-22 09:49:37,463: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:49:37,825: Re-connection
[rosout][INFO] 2015-05-22 09:49:46,751: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:49:48,968: Re-connection
[rosout][INFO] 2015-05-22 09:50:05,967: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:50:06,104: Re-connection
[rosout][INFO] 2015-05-22 09:50:10,765: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:50:13,165: Re-connection
[rosout][INFO] 2015-05-22 09:50:38,717: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:50:41,185: Re-connection
[rosout][INFO] 2015-05-22 09:50:50,970: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:50:51,011: Re-connection
[rosout][INFO] 2015-05-22 09:50:57,671: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:51:00,078: Re-connection
[rosout][INFO] 2015-05-22 09:51:11,593: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:51:11,617: Re-connection
[rosout][INFO] 2015-05-22 09:51:13,802: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:51:16,233: Re-connection
[rosout][INFO] 2015-05-22 09:51:27,847: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:51:30,323: Re-connection
[rosout][INFO] 2015-05-22 09:51:37,870: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:51:38,018: Re-connection
[rosout][INFO] 2015-05-22 09:51:43,563: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:51:43,576: Re-connection
[rosout][INFO] 2015-05-22 09:51:49,612: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:51:52,032: Re-connection
[rosout][INFO] 2015-05-22 09:52:07,552: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:52:07,947: Re-connection
[rosout][INFO] 2015-05-22 09:52:09,264: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:52:11,694: Re-connection
[rosout][INFO] 2015-05-22 09:52:17,722: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:52:17,976: Re-connection
[rosout][INFO] 2015-05-22 09:52:18,386: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:52:18,447: Re-connection
[rosout][INFO] 2015-05-22 09:52:29,004: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:52:31,486: Re-connection
[rosout][INFO] 2015-05-22 09:53:09,111: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:53:11,624: Re-connection
[rosout][INFO] 2015-05-22 09:53:29,343: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:53:31,815: Re-connection
[rosout][INFO] 2015-05-22 09:53:47,516: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:53:49,937: Re-connection
[rosout][INFO] 2015-05-22 09:54:05,873: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:54:08,310: Re-connection
[rosout][INFO] 2015-05-22 09:54:16,238: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:54:16,305: Re-connection
[rosout][INFO] 2015-05-22 09:54:23,904: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:54:26,382: Re-connection
[rosout][INFO] 2015-05-22 09:54:41,882: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:54:44,312: Re-connection
[rosout][INFO] 2015-05-22 09:54:59,787: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:55:02,168: Re-connection
[rosout][INFO] 2015-05-22 09:55:18,546: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:55:20,976: Re-connection
[rosout][INFO] 2015-05-22 09:56:27,957: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:56:27,963: Re-connection
[rosout][INFO] 2015-05-22 09:58:45,856: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 09:58:45,951: Re-connection
[rosout][INFO] 2015-05-22 10:00:35,950: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:00:37,872: Re-connection
[rosout][INFO] 2015-05-22 10:00:56,094: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:00:56,155: Re-connection
[rosout][INFO] 2015-05-22 10:01:27,912: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:01:28,033: Re-connection
[rosout][INFO] 2015-05-22 10:01:28,433: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:01:28,562: Re-connection
[rosout][INFO] 2015-05-22 10:01:28,964: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:01:29,153: Re-connection
[rosout][INFO] 2015-05-22 10:01:56,900: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:01:56,945: Re-connection
[rosout][INFO] 2015-05-22 10:02:02,842: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:02:04,641: Re-connection
[rosout][INFO] 2015-05-22 10:02:32,631: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:02:34,558: Re-connection
[rospy.internal][INFO] 2015-05-22 10:04:29,538: topic[/stop_learning] adding connection to [http://192.168.1.13:39199/], count 0
[rospy.internal][ERROR] 2015-05-22 10:04:29,577: Unable to initiate TCP/IP socket to 192.168.1.13:39494 (http://192.168.1.13:41917/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 10:04:29,580: topic[/activity_time] adding connection to [/emotional_manager], count 1
[rospy.internal][INFO] 2015-05-22 10:04:29,580: topic[/activity_time] removing connection to /emotional_manager
[rosout][INFO] 2015-05-22 10:04:30,560: STATE: STOPPING
[rospy.internal][WARNING] 2015-05-22 10:04:30,580: Unknown error initiating TCP/IP socket to 192.168.1.13:39494 (http://192.168.1.13:41917/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 10:04:30,580: topic[/activity] removing connection to http://192.168.1.13:41917/
[rospy.internal][ERROR] 2015-05-22 10:04:32,508: Unable to initiate TCP/IP socket to 192.168.1.13:48860 (http://192.168.1.13:39199/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 10:04:33,508: Unknown error initiating TCP/IP socket to 192.168.1.13:48860 (http://192.168.1.13:39199/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 10:04:33,509: topic[/stop_learning] removing connection to http://192.168.1.13:39199/
[rospy.internal][INFO] 2015-05-22 10:04:33,627: topic[/activity] adding connection to [/joke_nao], count 6
[rospy.internal][INFO] 2015-05-22 10:04:33,628: topic[/activity] removing connection to /joke_nao
[rospy.internal][ERROR] 2015-05-22 10:04:33,634: Unable to initiate TCP/IP socket to 192.168.1.13:33451 (http://192.168.1.13:54529/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 10:04:34,636: Unknown error initiating TCP/IP socket to 192.168.1.13:33451 (http://192.168.1.13:54529/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 10:04:34,637: topic[/activity] removing connection to http://192.168.1.13:54529/
[rospy.core][INFO] 2015-05-22 10:04:38,974: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 10:04:38,986: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 10:04:38,987: topic[/activity] removing connection to /activity_manager
[rospy.internal][ERROR] 2015-05-22 10:04:38,988: Unable to initiate TCP/IP socket to 192.168.1.13:50692 (http://192.168.1.13:50638/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 10:04:38,988: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 10:04:38,989: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 10:04:38,989: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 10:04:38,989: topic[/activity] removing connection to /action_manager
[rospy.internal][INFO] 2015-05-22 10:04:38,989: topic[/activity] removing connection to /joke_nao
[rospy.internal][INFO] 2015-05-22 10:04:38,989: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][INFO] 2015-05-22 10:04:38,989: topic[/activity] removing connection to http://192.168.1.13:50638/
[rospy.internal][INFO] 2015-05-22 10:04:38,990: topic[/activity] removing connection to http://192.168.1.16:53703/
[rospy.internal][INFO] 2015-05-22 10:04:38,990: topic[/watchdog_clear/tablet] removing connection to http://192.168.1.3:33845/
[rospy.topics][ERROR] 2015-05-22 10:04:38,991: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2015-05-22 10:04:38,991: Interaction exited
[rospy.internal][WARNING] 2015-05-22 10:04:38,993: Unknown error initiating TCP/IP socket to 192.168.1.3:37672 (http://192.168.1.3:33845/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rosout][INFO] 2015-05-22 10:04:39,377: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:04:39,606: Stopped
[rospy.core][INFO] 2015-05-22 10:04:39,638: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 10:31:21,233: init_node, name[/activity_manager], pid[5897]
[xmlrpc][INFO] 2015-05-22 10:31:21,233: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2015-05-22 10:31:21,234: ROS Slave URI: [http://192.168.1.13:39948/]
[xmlrpc][INFO] 2015-05-22 10:31:21,234: Started XML-RPC server [http://192.168.1.13:39948/]
[rospy.impl.masterslave][INFO] 2015-05-22 10:31:21,234: _ready: http://192.168.1.13:39948/
[xmlrpc][INFO] 2015-05-22 10:31:21,235: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 10:31:21,235: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 10:31:21,334: registered with master
[rospy.rosout][INFO] 2015-05-22 10:31:21,335: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 10:31:21,337: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 10:31:21,339: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 10:31:21,357: Starting new timer
[rosout][INFO] 2015-05-22 10:31:21,358: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 10:31:21,401: topic[/activity] adding connection to [http://192.168.1.13:39948/], count 0
[rospy.internal][INFO] 2015-05-22 10:31:21,403: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 10:31:21,435: topic[/watchdog_clear/tablet] adding connection to [http://192.168.1.3:33845/], count 0
[rospy.internal][INFO] 2015-05-22 10:31:21,453: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2015-05-22 10:31:21,543: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 10:31:21,584: topic[/activity] adding connection to [http://192.168.1.16:51061/], count 1
[rospy.internal][INFO] 2015-05-22 10:31:21,875: topic[/activity] adding connection to [/rosjava_tutorial_pubsub/listener], count 2
[rospy.internal][INFO] 2015-05-22 10:31:22,179: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2015-05-22 10:31:22,223: topic[/activity] adding connection to [http://192.168.1.13:41045/], count 2
[rospy.internal][INFO] 2015-05-22 10:31:22,250: topic[/activity] adding connection to [/joke_nao], count 4
[rospy.internal][INFO] 2015-05-22 10:31:22,262: topic[/activity] adding connection to [/learning_words_nao], count 5
[rosout][INFO] 2015-05-22 10:31:23,360: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 10:31:23,928: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:31:23,932: Re-connection
[rosout][INFO] 2015-05-22 10:31:24,925: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 10:31:25,427: STATE: STARTING_INTERACTION
[rospy.internal][INFO] 2015-05-22 10:31:33,436: topic[/activity] adding connection to [/action_manager], count 6
[rospy.internal][INFO] 2015-05-22 10:31:33,467: topic[/activity_time] adding connection to [/emotional_manager], count 0
[rosout][INFO] 2015-05-22 10:31:33,489: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rospy.internal][INFO] 2015-05-22 10:31:33,554: topic[/activity] adding connection to [http://192.168.1.13:44461/], count 3
[rosout][INFO] 2015-05-22 10:31:34,991: STATE: ACTIVITY
[rospy.internal][INFO] 2015-05-22 10:32:09,230: topic[/stop_learning] adding connection to [http://192.168.1.13:35265/], count 0
[rospy.internal][ERROR] 2015-05-22 10:32:09,233: Unable to initiate TCP/IP socket to 192.168.1.13:38196 (http://192.168.1.13:44461/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 10:32:09,240: topic[/activity_time] adding connection to [/emotional_manager], count 1
[rospy.internal][INFO] 2015-05-22 10:32:09,240: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][WARNING] 2015-05-22 10:32:10,234: Unknown error initiating TCP/IP socket to 192.168.1.13:38196 (http://192.168.1.13:44461/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 10:32:10,235: topic[/activity] removing connection to http://192.168.1.13:44461/
[rosout][INFO] 2015-05-22 10:32:11,028: STATE: STOPPING
[rospy.internal][ERROR] 2015-05-22 10:32:12,203: Unable to initiate TCP/IP socket to 192.168.1.13:41020 (http://192.168.1.13:35265/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 10:32:13,205: Unknown error initiating TCP/IP socket to 192.168.1.13:41020 (http://192.168.1.13:35265/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 10:32:13,205: topic[/stop_learning] removing connection to http://192.168.1.13:35265/
[rospy.internal][ERROR] 2015-05-22 10:32:13,424: Unable to initiate TCP/IP socket to 192.168.1.13:40488 (http://192.168.1.13:41045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 10:32:14,426: Unknown error initiating TCP/IP socket to 192.168.1.13:40488 (http://192.168.1.13:41045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 10:32:14,426: topic[/activity] removing connection to http://192.168.1.13:41045/
[rospy.core][INFO] 2015-05-22 10:32:16,656: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 10:32:16,667: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 10:32:16,667: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2015-05-22 10:32:16,668: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 10:32:16,669: topic[/activity] removing connection to /rosjava_tutorial_pubsub/listener
[rospy.internal][ERROR] 2015-05-22 10:32:16,669: Unable to initiate TCP/IP socket to 192.168.1.13:59437 (http://192.168.1.13:39948/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 10:32:16,670: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 10:32:16,670: topic[/activity] removing connection to /joke_nao
[rospy.internal][INFO] 2015-05-22 10:32:16,670: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 10:32:16,671: topic[/activity] removing connection to /action_manager
[rospy.internal][INFO] 2015-05-22 10:32:16,671: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][INFO] 2015-05-22 10:32:16,671: topic[/activity] removing connection to http://192.168.1.13:39948/
[rospy.internal][INFO] 2015-05-22 10:32:16,671: topic[/activity] removing connection to http://192.168.1.16:51061/
[rospy.internal][INFO] 2015-05-22 10:32:16,672: topic[/watchdog_clear/tablet] removing connection to http://192.168.1.3:33845/
[rospy.impl.masterslave][INFO] 2015-05-22 10:32:16,672: Interaction exited
[rosout][INFO] 2015-05-22 10:32:16,776: Stopped
[rospy.core][INFO] 2015-05-22 10:32:16,804: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 10:40:33,568: init_node, name[/activity_manager], pid[9066]
[xmlrpc][INFO] 2015-05-22 10:40:33,575: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 10:40:33,575: Started XML-RPC server [http://192.168.1.13:45475/]
[rospy.impl.masterslave][INFO] 2015-05-22 10:40:33,576: _ready: http://192.168.1.13:45475/
[rospy.init][INFO] 2015-05-22 10:40:33,576: ROS Slave URI: [http://192.168.1.13:45475/]
[xmlrpc][INFO] 2015-05-22 10:40:33,576: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 10:40:33,576: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 10:40:33,677: registered with master
[rospy.rosout][INFO] 2015-05-22 10:40:33,678: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 10:40:33,680: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 10:40:33,681: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 10:40:33,721: Starting new timer
[rosout][INFO] 2015-05-22 10:40:33,722: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 10:40:33,753: topic[/activity] adding connection to [http://192.168.1.13:45475/], count 0
[rospy.internal][INFO] 2015-05-22 10:40:33,760: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 10:40:33,819: topic[/watchdog_clear/tablet] adding connection to [http://192.168.1.3:33845/], count 0
[rospy.internal][INFO] 2015-05-22 10:40:33,827: topic[/activity] adding connection to [http://192.168.1.16:51061/], count 1
[rospy.internal][INFO] 2015-05-22 10:40:33,870: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 10:40:33,974: topic[/activity] adding connection to [/rosjava_tutorial_pubsub/listener], count 1
[rospy.internal][INFO] 2015-05-22 10:40:34,000: topic[/activity] adding connection to [/log], count 2
[rospy.internal][INFO] 2015-05-22 10:40:34,854: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2015-05-22 10:40:34,967: topic[/activity] adding connection to [http://192.168.1.13:34018/], count 2
[rospy.internal][INFO] 2015-05-22 10:40:35,141: topic[/activity] adding connection to [/joke_nao], count 4
[rospy.internal][INFO] 2015-05-22 10:40:35,288: topic[/activity] adding connection to [/learning_words_nao], count 5
[rosout][INFO] 2015-05-22 10:40:35,431: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:40:35,509: Re-connection
[rosout][INFO] 2015-05-22 10:40:35,724: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 10:40:35,955: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:40:36,761: Re-connection
[rosout][INFO] 2015-05-22 10:40:37,480: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 10:40:37,981: STATE: STARTING_INTERACTION
[rosout][INFO] 2015-05-22 10:40:46,021: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 10:40:47,523: STATE: ACTIVITY
[rospy.internal][INFO] 2015-05-22 10:40:53,971: topic[/activity] adding connection to [/action_manager], count 6
[rospy.internal][INFO] 2015-05-22 10:40:53,998: topic[/activity_time] adding connection to [/emotional_manager], count 0
[rospy.internal][INFO] 2015-05-22 10:40:54,085: topic[/activity] adding connection to [http://192.168.1.13:48821/], count 3
[rosout][INFO] 2015-05-22 10:43:35,363: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:43:37,853: Re-connection
[rosout][INFO] 2015-05-22 10:44:19,080: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:44:21,450: Re-connection
[rosout][INFO] 2015-05-22 10:44:47,057: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:44:49,508: Re-connection
[rosout][INFO] 2015-05-22 10:45:15,919: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:45:18,384: Re-connection
[rosout][INFO] 2015-05-22 10:45:30,466: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:45:30,477: Re-connection
[rosout][INFO] 2015-05-22 10:45:45,015: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:45:47,665: Re-connection
[rosout][INFO] 2015-05-22 10:46:10,878: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:46:13,044: Re-connection
[rosout][INFO] 2015-05-22 10:46:34,009: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:46:34,111: Re-connection
[rosout][INFO] 2015-05-22 10:46:39,839: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:46:42,274: Re-connection
[rosout][INFO] 2015-05-22 10:47:14,626: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:47:17,074: Re-connection
[rosout][INFO] 2015-05-22 10:47:37,990: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:47:40,441: Re-connection
[rosout][INFO] 2015-05-22 10:48:09,665: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:48:11,895: Re-connection
[rosout][INFO] 2015-05-22 10:49:06,616: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:49:06,747: Re-connection
[rosout][INFO] 2015-05-22 10:49:11,576: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:49:11,579: Re-connection
[rosout][INFO] 2015-05-22 10:49:12,367: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:49:14,311: Re-connection
[rosout][INFO] 2015-05-22 10:49:36,381: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:49:38,835: Re-connection
[rosout][INFO] 2015-05-22 10:49:59,277: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:50:01,772: Re-connection
[rosout][INFO] 2015-05-22 10:50:22,352: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:50:24,806: Re-connection
[rosout][INFO] 2015-05-22 10:50:41,912: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:50:42,020: Re-connection
[rosout][INFO] 2015-05-22 10:50:46,346: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:50:48,833: Re-connection
[rosout][INFO] 2015-05-22 10:51:02,596: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:51:05,029: Re-connection
[rosout][INFO] 2015-05-22 10:51:28,361: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:51:30,799: Re-connection
[rosout][INFO] 2015-05-22 10:51:53,447: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:51:55,957: Re-connection
[rosout][INFO] 2015-05-22 10:52:10,189: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:52:10,289: Re-connection
[rosout][INFO] 2015-05-22 10:52:18,716: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:52:21,218: Re-connection
[rosout][INFO] 2015-05-22 10:52:39,257: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:52:39,303: Re-connection
[rosout][INFO] 2015-05-22 10:52:44,583: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:52:47,028: Re-connection
[rosout][INFO] 2015-05-22 10:53:07,038: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:53:09,421: Re-connection
[rosout][INFO] 2015-05-22 10:53:30,869: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:53:33,350: Re-connection
[rosout][INFO] 2015-05-22 10:53:53,889: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:53:56,278: Re-connection
[rosout][INFO] 2015-05-22 10:55:12,584: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:55:14,884: Re-connection
[rosout][INFO] 2015-05-22 10:55:39,561: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:55:42,108: Re-connection
[rosout][INFO] 2015-05-22 10:56:23,003: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:56:25,476: Re-connection
[rosout][INFO] 2015-05-22 10:56:48,585: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:56:50,967: Re-connection
[rosout][INFO] 2015-05-22 10:57:11,131: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:57:13,520: Re-connection
[rosout][INFO] 2015-05-22 10:57:32,190: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:57:34,588: Re-connection
[rosout][INFO] 2015-05-22 10:57:53,020: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:57:55,240: Re-connection
[rosout][INFO] 2015-05-22 10:58:21,696: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:58:24,017: Re-connection
[rosout][INFO] 2015-05-22 10:58:43,912: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:58:46,406: Re-connection
[rosout][INFO] 2015-05-22 10:59:03,187: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:59:05,580: Re-connection
[rosout][INFO] 2015-05-22 10:59:29,047: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 10:59:31,520: Re-connection
[rosout][INFO] 2015-05-22 11:00:45,782: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 11:00:45,798: Re-connection
[rosout][INFO] 2015-05-22 11:00:50,066: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 11:00:50,116: Re-connection
[rosout][INFO] 2015-05-22 11:02:14,647: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 11:02:17,113: Re-connection
[rosout][INFO] 2015-05-22 11:02:50,643: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 11:02:53,107: Re-connection
[rosout][INFO] 2015-05-22 11:03:11,599: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 11:03:11,652: Re-connection
[rospy.internal][INFO] 2015-05-22 11:05:10,930: topic[/stop_learning] adding connection to [http://192.168.1.13:34277/], count 0
[rospy.internal][ERROR] 2015-05-22 11:05:10,953: Unable to initiate TCP/IP socket to 192.168.1.13:46021 (http://192.168.1.13:48821/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 11:05:11,954: Unknown error initiating TCP/IP socket to 192.168.1.13:46021 (http://192.168.1.13:48821/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 11:05:11,954: topic[/activity] removing connection to http://192.168.1.13:48821/
[rosout][INFO] 2015-05-22 11:05:12,884: STATE: STOPPING
[rospy.internal][ERROR] 2015-05-22 11:05:13,849: Unable to initiate TCP/IP socket to 192.168.1.13:55646 (http://192.168.1.13:34277/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 11:05:14,850: Unknown error initiating TCP/IP socket to 192.168.1.13:55646 (http://192.168.1.13:34277/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 11:05:14,850: topic[/stop_learning] removing connection to http://192.168.1.13:34277/
[rospy.internal][INFO] 2015-05-22 11:05:14,876: topic[/activity] adding connection to [/joke_nao], count 7
[rospy.internal][ERROR] 2015-05-22 11:05:14,876: Unable to initiate TCP/IP socket to 192.168.1.13:46967 (http://192.168.1.13:34018/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 11:05:14,877: topic[/activity] removing connection to /joke_nao
[rospy.internal][WARNING] 2015-05-22 11:05:15,878: Unknown error initiating TCP/IP socket to 192.168.1.13:46967 (http://192.168.1.13:34018/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 11:05:15,878: topic[/activity] removing connection to http://192.168.1.13:34018/
[rospy.core][INFO] 2015-05-22 11:05:22,494: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 11:05:22,505: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 11:05:22,505: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2015-05-22 11:05:22,506: topic[/activity] removing connection to /rosjava_tutorial_pubsub/listener
[rospy.internal][ERROR] 2015-05-22 11:05:22,508: Unable to initiate TCP/IP socket to 192.168.1.13:55859 (http://192.168.1.13:45475/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 11:05:22,508: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 11:05:22,509: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 11:05:22,509: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 11:05:22,510: topic[/activity] removing connection to /action_manager
[rospy.internal][INFO] 2015-05-22 11:05:22,510: topic[/activity] removing connection to /joke_nao
[rospy.internal][INFO] 2015-05-22 11:05:22,510: topic[/activity_time] removing connection to /emotional_manager
[rospy.internal][INFO] 2015-05-22 11:05:22,511: topic[/activity] removing connection to http://192.168.1.13:45475/
[rospy.internal][INFO] 2015-05-22 11:05:22,511: topic[/activity] removing connection to http://192.168.1.16:51061/
[rospy.internal][INFO] 2015-05-22 11:05:22,512: topic[/watchdog_clear/tablet] removing connection to http://192.168.1.3:33845/
[rospy.impl.masterslave][INFO] 2015-05-22 11:05:22,512: Interaction exited
[rosout][INFO] 2015-05-22 11:05:22,894: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 11:05:23,127: Stopped
[rospy.core][INFO] 2015-05-22 11:05:23,152: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 12:03:02,674: init_node, name[/activity_manager], pid[8281]
[xmlrpc][INFO] 2015-05-22 12:03:02,675: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2015-05-22 12:03:02,676: ROS Slave URI: [http://192.168.1.13:38449/]
[xmlrpc][INFO] 2015-05-22 12:03:02,675: Started XML-RPC server [http://192.168.1.13:38449/]
[rospy.impl.masterslave][INFO] 2015-05-22 12:03:02,676: _ready: http://192.168.1.13:38449/
[xmlrpc][INFO] 2015-05-22 12:03:02,676: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 12:03:02,676: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 12:03:02,776: registered with master
[rospy.rosout][INFO] 2015-05-22 12:03:02,776: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 12:03:02,778: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 12:03:02,780: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 12:03:02,795: Starting new timer
[rosout][INFO] 2015-05-22 12:03:02,798: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 12:03:02,798: topic[/activity] adding connection to [http://192.168.1.13:38449/], count 0
[rospy.internal][INFO] 2015-05-22 12:03:02,801: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 12:03:02,827: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2015-05-22 12:03:02,859: topic[/activity] adding connection to [http://192.168.1.16:40767/], count 1
[rospy.internal][INFO] 2015-05-22 12:03:02,898: topic[/watchdog_clear/tablet] adding connection to [http://192.168.1.3:33845/], count 0
[rospy.internal][INFO] 2015-05-22 12:03:03,023: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 12:03:03,289: topic[/activity] adding connection to [/rosjava_tutorial_pubsub/listener], count 2
[rospy.internal][INFO] 2015-05-22 12:03:03,903: topic[/activity] adding connection to [/learning_words_nao], count 3
[rospy.internal][INFO] 2015-05-22 12:03:04,042: topic[/activity] adding connection to [/joke_nao], count 4
[rospy.internal][INFO] 2015-05-22 12:03:04,064: topic[/activity] adding connection to [/drawing_nao], count 5
[rospy.internal][INFO] 2015-05-22 12:03:04,169: topic[/activity] adding connection to [http://192.168.1.13:34856/], count 2
[rosout][INFO] 2015-05-22 12:03:04,800: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 12:03:05,641: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:03:05,643: Re-connection
[rosout][INFO] 2015-05-22 12:03:06,546: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 12:03:07,047: STATE: STARTING_INTERACTION
[rosout][INFO] 2015-05-22 12:03:15,641: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 12:03:17,144: STATE: ACTIVITY
[rosout][INFO] 2015-05-22 12:03:58,856: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:04:01,367: Re-connection
[rosout][INFO] 2015-05-22 12:04:03,789: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:04:03,795: Re-connection
[rosout][INFO] 2015-05-22 12:05:10,732: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:05:10,821: Re-connection
[rosout][INFO] 2015-05-22 12:05:11,577: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:05:11,797: Re-connection
[rosout][INFO] 2015-05-22 12:05:40,472: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:05:42,615: Re-connection
[rospy.internal][INFO] 2015-05-22 12:06:05,480: topic[/stop_learning] adding connection to [http://192.168.1.13:58036/], count 0
[rosout][INFO] 2015-05-22 12:06:06,817: STATE: STOPPING
[rospy.internal][WARNING] 2015-05-22 12:06:08,376: Unknown error initiating TCP/IP socket to 192.168.1.13:41687 (http://192.168.1.13:58036/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 607, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 419, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2015-05-22 12:06:08,376: topic[/stop_learning] removing connection to http://192.168.1.13:58036/
[rospy.internal][ERROR] 2015-05-22 12:06:10,796: Unable to initiate TCP/IP socket to 192.168.1.13:36097 (http://192.168.1.13:34856/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 12:06:11,798: Unknown error initiating TCP/IP socket to 192.168.1.13:36097 (http://192.168.1.13:34856/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 12:06:11,798: topic[/activity] removing connection to http://192.168.1.13:34856/
[rospy.core][INFO] 2015-05-22 12:06:12,521: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 12:06:12,531: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 12:06:12,532: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2015-05-22 12:06:12,532: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 12:06:12,533: topic[/activity] removing connection to /rosjava_tutorial_pubsub/listener
[rospy.internal][INFO] 2015-05-22 12:06:12,533: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][ERROR] 2015-05-22 12:06:12,534: Unable to initiate TCP/IP socket to 192.168.1.13:47503 (http://192.168.1.13:38449/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 12:06:12,534: topic[/activity] removing connection to /joke_nao
[rospy.internal][INFO] 2015-05-22 12:06:12,534: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 12:06:12,535: topic[/activity] removing connection to http://192.168.1.13:38449/
[rospy.internal][INFO] 2015-05-22 12:06:12,535: topic[/activity] removing connection to http://192.168.1.16:40767/
[rospy.internal][INFO] 2015-05-22 12:06:12,535: topic[/watchdog_clear/tablet] removing connection to http://192.168.1.3:33845/
[rospy.impl.masterslave][INFO] 2015-05-22 12:06:12,535: Interaction exited
[rosout][INFO] 2015-05-22 12:06:12,924: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:06:13,150: Stopped
[rospy.core][INFO] 2015-05-22 12:06:13,181: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 12:06:25,472: init_node, name[/activity_manager], pid[16523]
[xmlrpc][INFO] 2015-05-22 12:06:25,473: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 12:06:25,474: Started XML-RPC server [http://192.168.1.13:51304/]
[rospy.impl.masterslave][INFO] 2015-05-22 12:06:25,474: _ready: http://192.168.1.13:51304/
[rospy.init][INFO] 2015-05-22 12:06:25,474: ROS Slave URI: [http://192.168.1.13:51304/]
[rospy.registration][INFO] 2015-05-22 12:06:25,475: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2015-05-22 12:06:25,476: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2015-05-22 12:06:25,575: registered with master
[rospy.rosout][INFO] 2015-05-22 12:06:25,575: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 12:06:25,577: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 12:06:25,579: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 12:06:25,606: Starting new timer
[rosout][INFO] 2015-05-22 12:06:25,607: Waiting for display manager services to become available
[rospy.internal][INFO] 2015-05-22 12:06:25,646: topic[/activity] adding connection to [http://192.168.1.13:51304/], count 0
[rospy.internal][INFO] 2015-05-22 12:06:25,648: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2015-05-22 12:06:25,665: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2015-05-22 12:06:25,703: topic[/activity] adding connection to [http://192.168.1.16:40767/], count 1
[rospy.internal][INFO] 2015-05-22 12:06:25,711: topic[/watchdog_clear/tablet] adding connection to [http://192.168.1.3:33845/], count 0
[rospy.internal][INFO] 2015-05-22 12:06:25,730: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 12:06:26,032: topic[/activity] adding connection to [/rosjava_tutorial_pubsub/listener], count 2
[rospy.internal][INFO] 2015-05-22 12:06:26,437: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2015-05-22 12:06:26,562: topic[/activity] adding connection to [http://192.168.1.13:56267/], count 2
[rospy.internal][INFO] 2015-05-22 12:06:26,581: topic[/activity] adding connection to [/joke_nao], count 4
[rospy.internal][INFO] 2015-05-22 12:06:26,795: topic[/activity] adding connection to [/learning_words_nao], count 5
[rosout][INFO] 2015-05-22 12:06:27,342: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:06:27,529: Re-connection
[rosout][INFO] 2015-05-22 12:06:27,608: Nao configuration: writing=True, speaking=True (french), standing=True, handedness=right
[rosout][INFO] 2015-05-22 12:06:29,084: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2015-05-22 12:06:29,586: STATE: STARTING_INTERACTION
[rosout][INFO] 2015-05-22 12:06:37,255: NAO: Bonjour, je suis Mimi. Je voudrais apprendre Ã  dessiner des chiffres.
[rosout][INFO] 2015-05-22 12:06:38,758: STATE: ACTIVITY
[rosout][INFO] 2015-05-22 12:06:46,883: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:06:49,340: Re-connection
[rosout][INFO] 2015-05-22 12:07:32,678: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:07:35,116: Re-connection
[rosout][INFO] 2015-05-22 12:08:45,495: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:08:45,498: Re-connection
[rosout][INFO] 2015-05-22 12:08:47,782: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2015-05-22 12:08:48,647: Re-connection
[rospy.internal][WARNING] 2015-05-22 12:13:32,225: Unknown error initiating TCP/IP socket to 192.168.1.16:39807 (http://192.168.1.16:40767/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 12:13:32,226: topic[/activity] removing connection to http://192.168.1.16:40767/
[rospy.internal][INFO] 2015-05-22 12:13:32,313: topic[/activity] adding connection to [http://192.168.1.16:33279/], count 2
[rosout][INFO] 2015-05-22 12:14:07,624: Haven't received a clear on 'watchdog_clear/tablet' topic
[rospy.internal][ERROR] 2015-05-22 12:16:02,671: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 110] Connection timed out

[rospy.internal][WARNING] 2015-05-22 12:16:05,671: Unknown error initiating TCP/IP socket to 192.168.1.16:55484 (http://192.168.1.16:33279/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 113] No route to host

[rospy.internal][INFO] 2015-05-22 12:16:05,672: topic[/activity] removing connection to http://192.168.1.16:33279/
[rospy.internal][ERROR] 2015-05-22 12:16:37,487: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 110] Connection timed out

[rospy.internal][WARNING] 2015-05-22 12:17:07,517: Unknown error initiating TCP/IP socket to 192.168.1.3:37672 (http://192.168.1.3:33845/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

[rospy.internal][INFO] 2015-05-22 12:17:07,518: topic[/watchdog_clear/tablet] removing connection to http://192.168.1.3:33845/
[rospy.internal][ERROR] 2015-05-22 12:17:58,127: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 110] Connection timed out

[rospy.internal][ERROR] 2015-05-22 12:18:09,903: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 110] Connection timed out

[rospy.core][INFO] 2015-05-22 12:18:15,798: signal_shutdown [signal-2]
[rospy.internal][INFO] 2015-05-22 12:18:15,818: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 12:18:15,818: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2015-05-22 12:18:15,818: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2015-05-22 12:18:15,818: topic[/activity] removing connection to /rosjava_tutorial_pubsub/listener
[rospy.internal][INFO] 2015-05-22 12:18:15,818: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2015-05-22 12:18:15,818: topic[/activity] removing connection to /joke_nao
[rospy.internal][INFO] 2015-05-22 12:18:15,819: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2015-05-22 12:18:15,819: topic[/activity] removing connection to http://192.168.1.13:51304/
[rospy.internal][WARNING] 2015-05-22 12:18:15,819: Unknown error initiating TCP/IP socket to 192.168.1.13:34611 (http://192.168.1.13:51304/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2015-05-22 12:18:15,819: topic[/activity] removing connection to http://192.168.1.13:56267/
[rospy.internal][WARNING] 2015-05-22 12:18:15,819: Unknown error initiating TCP/IP socket to 192.168.1.13:51984 (http://192.168.1.13:56267/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.impl.masterslave][INFO] 2015-05-22 12:18:15,819: signal-2
[rospy.core][INFO] 2015-05-22 12:18:30,825: signal_shutdown [signal-15]
